package Pojo;
// Generated Apr 25, 2017 3:44:08 PM by Hibernate Tools 4.3.1



/**
 * AttendanceId generated by hbm2java
 */
public class AttendanceId  implements java.io.Serializable {


     private int id;
     private int week;

    public AttendanceId() {
    }

    public AttendanceId(int id, int week) {
       this.id = id;
       this.week = week;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getWeek() {
        return this.week;
    }
    
    public void setWeek(int week) {
        this.week = week;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AttendanceId) ) return false;
		 AttendanceId castOther = ( AttendanceId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getWeek()==castOther.getWeek());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getWeek();
         return result;
   }   


}


