package Pojo;
// Generated Apr 25, 2017 3:44:08 PM by Hibernate Tools 4.3.1



/**
 * Attendance generated by hbm2java
 */
public class Attendance  implements java.io.Serializable {


     private AttendanceId id;
     private SubjectUser subjectUser;

    public Attendance() {
    }

    public Attendance(AttendanceId id, SubjectUser subjectUser) {
       this.id = id;
       this.subjectUser = subjectUser;
    }
   
    public AttendanceId getId() {
        return this.id;
    }
    
    public void setId(AttendanceId id) {
        this.id = id;
    }
    public SubjectUser getSubjectUser() {
        return this.subjectUser;
    }
    
    public void setSubjectUser(SubjectUser subjectUser) {
        this.subjectUser = subjectUser;
    }




}


