package Pojo;
// Generated Apr 25, 2017 3:44:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SubjectUser generated by hbm2java
 */
public class SubjectUser  implements java.io.Serializable {


     private Integer id;
     private Subject subject;
     private User user;
     private Set attendances = new HashSet(0);

    public SubjectUser() {
    }

	
    public SubjectUser(Subject subject, User user) {
        this.subject = subject;
        this.user = user;
    }
    public SubjectUser(Subject subject, User user, Set attendances) {
       this.subject = subject;
       this.user = user;
       this.attendances = attendances;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Set getAttendances() {
        return this.attendances;
    }
    
    public void setAttendances(Set attendances) {
        this.attendances = attendances;
    }




}


