package Pojo;
// Generated Apr 25, 2017 3:44:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String id;
     private String name;
     private String password;
     private int type;
     private Set subjectUsers = new HashSet(0);

    public User() {
    }

	
    public User(String id, String name, String password, int type) {
        this.id = id;
        this.name = name;
        this.password = password;
        this.type = type;
    }
    public User(String id, String name, String password, int type, Set subjectUsers) {
       this.id = id;
       this.name = name;
       this.password = password;
       this.type = type;
       this.subjectUsers = subjectUsers;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public Set getSubjectUsers() {
        return this.subjectUsers;
    }
    
    public void setSubjectUsers(Set subjectUsers) {
        this.subjectUsers = subjectUsers;
    }




}


